-- RedefineTables
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_VisualInspection" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "vehicleId" INTEGER NOT NULL,
    "conformityCertificate" INTEGER DEFAULT 1,
    "isTaxi" INTEGER DEFAULT 1,
    "isArmoured" INTEGER DEFAULT 1,
    "isSalvage" INTEGER DEFAULT 1,
    "isPolice" INTEGER DEFAULT 1,
    "fuelEconomy" INTEGER DEFAULT 1,
    "vehiclePaint" INTEGER DEFAULT 1,
    "vehicleChassis" INTEGER DEFAULT 1,
    "vehiclePlate" INTEGER DEFAULT 1,
    "installationPoints" INTEGER DEFAULT 1,
    "brakeSystem" INTEGER DEFAULT 1,
    "wiringSystem" INTEGER DEFAULT 1,
    "headLights" INTEGER DEFAULT 1,
    "parkingLights" INTEGER DEFAULT 1,
    "signalLights" INTEGER DEFAULT 1,
    "warningLights" INTEGER DEFAULT 1,
    "horn" INTEGER DEFAULT 1,
    "windshield" INTEGER DEFAULT 1,
    "wipers" INTEGER DEFAULT 1,
    "tinting" INTEGER DEFAULT 1,
    "mirrors" INTEGER DEFAULT 1,
    "doors" INTEGER DEFAULT 1,
    "tires" INTEGER DEFAULT 1,
    "nuts" INTEGER DEFAULT 1,
    "dashboardLights" INTEGER DEFAULT 1,
    "tailLights" INTEGER DEFAULT 1,
    "reverseLights" INTEGER DEFAULT 1,
    "rearPlateLight" INTEGER DEFAULT 1,
    "turnSignalLights" INTEGER DEFAULT 1,
    "brakeLights" INTEGER DEFAULT 1,
    "saftyBelts" INTEGER DEFAULT 1,
    "vehicleBody" INTEGER DEFAULT 1,
    "fireExtinguisher" INTEGER DEFAULT 1,
    "warningTriangle" INTEGER DEFAULT 1,
    "spareTire" INTEGER DEFAULT 1,
    "rustCorrosion" INTEGER DEFAULT 1,
    "sunVisors" INTEGER DEFAULT 1,
    "ballJoints" INTEGER DEFAULT 1,
    "mountingBase" INTEGER DEFAULT 1,
    "steeringCircuit" INTEGER DEFAULT 1,
    "steeringRods" INTEGER DEFAULT 1,
    "hosesPipes" INTEGER DEFAULT 1,
    "brakeDiscs" INTEGER DEFAULT 1,
    "brakeCylinders" INTEGER DEFAULT 1,
    "fittings" INTEGER DEFAULT 1,
    "stabilizerBar" INTEGER DEFAULT 1,
    "frontSuspension" INTEGER DEFAULT 1,
    "rearSuspension" INTEGER DEFAULT 1,
    "frontSprings" INTEGER DEFAULT 1,
    "rearSprings" INTEGER DEFAULT 1,
    "shockAbsorbers" INTEGER DEFAULT 1,
    "engineMountings" INTEGER DEFAULT 1,
    "gearMountings" INTEGER DEFAULT 1,
    "transimissionParts" INTEGER DEFAULT 1,
    "mufflers" INTEGER DEFAULT 1,
    "fuelTank" INTEGER DEFAULT 1,
    "speedometerCable" INTEGER DEFAULT 1,
    "chassis" INTEGER DEFAULT 1,
    "floorRust" INTEGER DEFAULT 1,
    "oilLeaks" INTEGER DEFAULT 1,
    "result" BOOLEAN DEFAULT true,
    "createdAt" DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "VisualInspection_vehicleId_fkey" FOREIGN KEY ("vehicleId") REFERENCES "Vehicle" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_VisualInspection" ("ballJoints", "brakeCylinders", "brakeDiscs", "brakeLights", "brakeSystem", "chassis", "conformityCertificate", "createdAt", "dashboardLights", "doors", "engineMountings", "fireExtinguisher", "fittings", "floorRust", "frontSprings", "frontSuspension", "fuelEconomy", "fuelTank", "gearMountings", "headLights", "horn", "hosesPipes", "id", "installationPoints", "isArmoured", "isPolice", "isSalvage", "isTaxi", "mirrors", "mountingBase", "mufflers", "nuts", "oilLeaks", "parkingLights", "rearPlateLight", "rearSprings", "rearSuspension", "result", "reverseLights", "rustCorrosion", "saftyBelts", "shockAbsorbers", "signalLights", "spareTire", "speedometerCable", "stabilizerBar", "steeringCircuit", "steeringRods", "sunVisors", "tailLights", "tinting", "tires", "transimissionParts", "turnSignalLights", "vehicleBody", "vehicleChassis", "vehicleId", "vehiclePaint", "vehiclePlate", "warningLights", "warningTriangle", "windshield", "wipers", "wiringSystem") SELECT "ballJoints", "brakeCylinders", "brakeDiscs", "brakeLights", "brakeSystem", "chassis", "conformityCertificate", "createdAt", "dashboardLights", "doors", "engineMountings", "fireExtinguisher", "fittings", "floorRust", "frontSprings", "frontSuspension", "fuelEconomy", "fuelTank", "gearMountings", "headLights", "horn", "hosesPipes", "id", "installationPoints", "isArmoured", "isPolice", "isSalvage", "isTaxi", "mirrors", "mountingBase", "mufflers", "nuts", "oilLeaks", "parkingLights", "rearPlateLight", "rearSprings", "rearSuspension", "result", "reverseLights", "rustCorrosion", "saftyBelts", "shockAbsorbers", "signalLights", "spareTire", "speedometerCable", "stabilizerBar", "steeringCircuit", "steeringRods", "sunVisors", "tailLights", "tinting", "tires", "transimissionParts", "turnSignalLights", "vehicleBody", "vehicleChassis", "vehicleId", "vehiclePaint", "vehiclePlate", "warningLights", "warningTriangle", "windshield", "wipers", "wiringSystem" FROM "VisualInspection";
DROP TABLE "VisualInspection";
ALTER TABLE "new_VisualInspection" RENAME TO "VisualInspection";
CREATE UNIQUE INDEX "VisualInspection_vehicleId_key" ON "VisualInspection"("vehicleId");
PRAGMA foreign_key_check;
PRAGMA foreign_keys=ON;
